### ISSUE TITLE
Player scaling does not work correctly below 1

### ISSUE THREAD

**Issue by JohanGhostWolf56426** [Jacob-Mango/DayZ-CommunityOnlineTools#175]
When changing the player's scale is set to anything below 1 (0.9 - 0.1). The height of the player is the same for 0.1 - 0.9. Camera is locked to the directions you were looking before getting scaled down.

https://github.com/user-attachments/assets/66fa8ccd-e20f-4e42-b0b1-1a6af8e46b01

https://github.com/user-attachments/assets/54b28d79-8396-445c-b1f7-a293ca4ed289

https://github.com/user-attachments/assets/685acc72-3779-480a-b3d4-a47094edb230

**Comment by LieutenantMaster** [comment]
fixed next update, thanks for the report

**Comment by JohanGhostWolf56426** [comment]
Sorry for the late feedback, just tested the scaling below 1. It works fine from 0.4 to 1, but 0.1 - 0.3 is still broken.
